### ISSUE TITLE
Upload defaults

### ISSUE THREAD

**Issue by tinseltunes** [esphome/esphome-flasher#12]
Hi, Not an issue, just a question.
What are the default upload settings please or is it dependent on the Bin file?
Ie Higher memory 160Mhz .

Thanks

**Comment by OttoWinter** [comment]
They are derived from the binary (and from the flash chip id).

ESPHome-Flasher is purposefully very minimal and does not expose these options. If you want to manually change those things you can use nodemcu-pyflasher (which this flasher is based on).
