### ISSUE TITLE
Small issue in Console window

### ISSUE THREAD

**Issue by stefanroelofs** [esphome/esphome-flasher#13]
The log window is the black area in esphome-flasher where the log messages are printed.

When I flash an esp8266, I see a log message that indicated the progress of flashing. 
Something like this: Writing at 0x00048000... (100 %)

This log message eats up all other log messages above it. 
So this log message moves up and deletes the messages above it.

**Comment by OttoWinter** [comment]
Please add what platform this is on (windows etc).

I do not see this happening on my system.

**Comment by stefanroelofs** [comment]
Im using ESPHome-Flasher-1.2.0-windows-x64
On a Windows 10 laptop
Flashing a Shelly1 device.

Here's a small clip of it happening:
https://youtu.be/VhshUZu4iE0

**Comment by sermayoral** [comment]
I have the same problem. Windows 10 x64 with all ESPs. Its a minor problem,..

**Comment by OttoWinter** [comment]
Hmm, don't know what it is; I checked with a windows 10 VM and it worked there. I'll try it on a real windows laptop when i get access to one (probably around next week)

**Comment by sermayoral** [comment]
@OttoWinter is an small issue, but i have recorded a video to show you the problem: https://youtu.be/m32L21GU8tE

Thanks!

**Comment by DavidDeSloovere** [comment]
I'm also seeing this on a recent Windows 10 build.
But flashing works, it's just cosmetics.
Keep up the great work Otto.

**Comment by drogfild** [comment]
I have had this also always with ESPHome Flasher. Now using Flasher 1.3.0 with Win10 ver 2004. Can it be that there is char in the "Writing" line that makes it to misbehave? Small issue, but would be nice to see whole log after flashing.
All other logging and flashing with this tool works perfectly. Really nice tool!

**Comment by sermayoral** [comment]
I think bumping esptool library to 3.0 will do the trick!
