### ISSUE TITLE
Permission Error 13

### ISSUE THREAD

**Issue by Tom-Neverwinter** [esphome/esphome-flasher#14]
Unexpected error: could not open port 'COM4': PermissionError(13, 'Access is denied.', None, 5)

tried multiple farad capacitors. 1,2,10. 50V (it is suggested to do this..... However, since putting full specs down, is hard, I dont know if voltage is relevant.... yay youtubers.... always give half the info)

windows 10, port is selected, application was run as admin
Driver is installed. arduino see's it clear as day. I can see the serial monitor data:

> 17:03:28.609 -> ets Jun  8 2016 00:22:57
17:03:28.609 -> 
17:03:28.609 -> rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
17:03:28.644 -> configsip: 0, SPIWP:0x00
17:03:28.644 -> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
17:03:28.644 -> mode:DIO, clock div:2
17:03:28.644 -> load:0x3fff0008,len:8
17:03:28.644 -> load:0x3fff0010,len:3480
17:03:28.644 -> load:0x40078000,len:7804
17:03:28.644 -> ho 0 tail 12 room 4
17:03:28.644 -> load:0x40080000,len:252
17:03:28.644 -> entry 0x40080034
17:03:28.644 -> [0;32mI (45) boot: ESP-IDF v2.0-3-gbef9896 2nd stage bootloader[0m
17:03:28.644 -> [0;32mI (46) boot: compile time 05:59:45[0m
17:03:28.678 -> [0;32mI (46) boot: Enabling RNG early entropy source...[0m
17:03:28.678 -> [0;32mI (64) boot: SPI Speed      : 40MHz[0m
17:03:28.678 -> [0;32mI (77) boot: SPI Mode       : DIO[0m
17:03:28.678 -> [0;32mI (89) boot: SPI Flash Size : 4MB[0m
17:03:28.678 -> [0;32mI (102) boot: Partition Table:[0m
17:03:28.678 -> [0;32mI (113) boot: ## Label            Usage          Type ST Offset   Length[0m
17:03:28.678 -> [0;32mI (136) boot:  0 phy_init         RF data          01 01 0000f000 00001000[0m
17:03:28.712 -> [0;32mI (159) boot:  1 otadata          OTA data         01 00 00010000 00002000[0m
17:03:28.712 -> [0;32mI (182) boot:  2 nvs              WiFi data        01 02 00012000 0000e000[0m
17:03:28.712 -> [0;32mI (206) boot:  3 at_customize     unknown          40 00 00020000 000e0000[0m
17:03:28.712 -> [0;32mI (229) boot:  4 ota_0            OTA app          00 10 00100000 00180000[0m
17:03:28.746 -> [0;32mI (252) boot:  5 ota_1            OTA app          00 11 00280000 00180000[0m
17:03:28.746 -> [0;32mI (276) boot: End of partition table[0m
17:03:28.746 -> [0;32mI (289) boot: Disabling RNG early entropy source...[0m
17:03:28.746 -> [0;32mI (306) boot: Loading app partition at offset 00100000[0m
17:03:29.129 -> [0;32mI (1481) boot: segment 0: paddr=0x00100018 vaddr=0x00000000 size=0x0ffe8 ( 65512) [0m
17:03:29.129 -> [0;32mI (1482) boot: segment 1: paddr=0x00110008 vaddr=0x3f400010 size=0x1c5f0 (116208) map[0m
17:03:29.129 -> [0;32mI (1498) boot: segment 2: paddr=0x0012c600 vaddr=0x3ffb0000 size=0x0215c (  8540) load[0m
17:03:29.129 -> [0;32mI (1528) boot: segment 3: paddr=0x0012e764 vaddr=0x40080000 size=0x00400 (  1024) load[0m
17:03:29.164 -> [0;32mI (1552) boot: segment 4: paddr=0x0012eb6c vaddr=0x40080400 size=0x1b028 (110632) load[0m
17:03:29.164 -> [0;32mI (1630) boot: segment 5: paddr=0x00149b9c vaddr=0x400c0000 size=0x00034 (    52) load[0m
17:03:29.164 -> [0;32mI (1632) boot: segment 6: paddr=0x00149bd8 vaddr=0x00000000 size=0x06430 ( 25648) [0m
17:03:29.198 -> [0;32mI (1648) boot: segment 7: paddr=0x00150010 vaddr=0x400d0018 size=0x7a56c (501100) map[0m
17:03:29.198 -> [0;32mI (1675) heap_alloc_caps: Initializing. RAM available for dynamic allocation:[0m
17:03:29.198 -> [0;32mI (1698) heap_alloc_caps: At 3FFBA6B8 len 00025948 (150 KiB): DRAM[0m
17:03:29.198 -> [0;32mI (1719) heap_alloc_caps: At 3FFE8000 len 00018000 (96 KiB): D/IRAM[0m
17:03:29.198 -> [0;32mI (1740) heap_alloc_caps: At 4009B428 len 00004BD8 (18 KiB): IRAM[0m
17:03:29.233 -> [0;32mI (1761) cpu_start: Pro cpu up.[0m
17:03:29.233 -> [0;32mI (1773) cpu_start: Single core mode[0m
17:03:29.233 -> [0;32mI (1786) cpu_start: Pro cpu start user code[0m
17:03:29.233 -> [0;32mI (1847) cpu_start: Starting scheduler on PRO CPU.[0m
17:03:29.268 -> [0;32mI (2087) uart: queue free spaces: 10[0m
17:03:29.268 -> Bin version:0.10.0

> 17:03:29.268 -> I (2088) wifi: wifi firmware version: c604573
> 17:03:29.268 -> I (2088) wifi: config NVS flash: enabled
> 17:03:29.268 -> I (2089) wifi: config nano formating: disabled
> 17:03:29.268 -> I (2097) wifi: Init dynamic tx buffer num: 32
> 17:03:29.268 -> I (2098) wifi: wifi driver task: 3ffc4eac, prio:23, stack:3584
> 17:03:29.300 -> I (2103) wifi: Init static rx buffer num: 10
> 17:03:29.300 -> I (2107) wifi: Init dynamic rx buffer num: 0
> 17:03:29.300 -> I (2111) wifi: Init rx ampdu len mblock:7
> 17:03:29.300 -> I (2115) wifi: Init lldesc rx ampdu entry mblock:4
> 17:03:29.300 -> I (2120) wifi: wifi power manager task: 0x3ffca254 prio: 21 stack: 2560
> 17:03:29.300 -> I (2126) wifi: wifi timer task: 3ffcb2d4, prio:22, stack:3584
> 17:03:29.300 -> [0;31mE (2131) phy_init: PHY data partition validated[0m
> 17:03:29.335 -> [0;32mI (2157) phy: phy_version: 329, Feb 22 2017, 15:58:07, 0, 0[0m
> 17:03:29.335 -> I (2158) wifi: mode : softAP (80:7d:3a:b7:78:f9)
> 17:03:29.335 -> I (2161) wifi: mode : sta (80:7d:3a:b7:78:f8) + softAP (80:7d:3a:b7:78:f9)
> 17:03:29.335 -> I (2164) wifi: mode : softAP (80:7d:3a:b7:78:f9)

when trying to upload it is clearly in download mode:

> 17:19:29.285 -> ets Jun  8 2016 00:22:57
> 17:19:29.285 -> 
> 17:19:29.285 -> rst:0x1 (POWERON_RESET),boot:0x3 (DOWNLOAD_BOOT(UART0/UART1/SDIO_REI_REO_V2))
> 17:19:29.285 -> waiting for download
> 17:19:35.855 -> ts Jun  8 2016 00:22:57
> 17:19:35.855 -> 
> 17:19:35.855 -> rst:0x1 (POWERON_RESET),boot:0x3 (DOWNLOAD_BOOT(UART0/UART1/SDIO_REI_REO_V2))
> 17:19:35.855 -> waiting for download

**Comment by meteorinca** [comment]
Had the same issue. Was working a few days ago. I fixed it by installing the usb-to-uart-bridge-vcp-drivers for Windows and rebooting the machine. It now works both through cmd and the GUI.

**Comment by OttoWinter** [comment]
Since this appears to be a driver issue and not esphomeflasher-specific, I will close.

**Comment by sabellwind** [comment]
Hey @OttoWinter 

I'm still experiencing this issue even after updating drivers, I wrote up a bit on the Hass forums

https://community.home-assistant.io/t/flashing-wemos-d1-mini-with-esphome-unexpected-error-could-not-open-port-com4-permissionerror-13-access-is-denied-none-5/175361?u=sabellwind

**Comment by jwodev** [comment]
Hi there,
I had the same issue, but it only occured when I pressed [Flash ESP] after I had pressed [View Logs]
When I start the tool, connect the ESP via FTDI232 (in my case ESP-32 IO0 grounded), select the serial port, select my bin file and then directly push [Flash ESP] it flashed without any problem.

**Comment by daes10** [comment]
I have the same issue like @jwodev and now without pressing the "view log" tab it worked for me.

**Comment by Tom-Neverwinter** [comment]
Solution was to use a different cable. 

The anker powerline I was using has a resistor that prevented it from writing to the board.

**Comment by SimonVleugels** [comment]
Not using an Anker cable did it for me.
