### ISSUE TITLE
"Timed out waiting for packet header" while flashing M5Stack Atom

### ISSUE THREAD

**Issue by timmmmmmmmm** [esphome/esphome-flasher#15]
I tried to flash a bin file using esphome-flasher 1.2.0 to my [M5Stack Atom](https://m5stack.com/products/atom-matrix-esp32-development-kit), but was getting the "Timed out waiting for packet header" after getting the basic chip identification data in the log. Both on macOS and Windows.

Flashing succeeded using esphome-flasher 1.1.0. I expect it has to do with the faster upload speed in 1.2.0.

**Comment by tathamoddie** [comment]
Experience the same issue here with 1.2.0 and M5Stack Atom Lite.

Works when reverting back to 1.1.0.

**Comment by mcflexus** [comment]
Experiencing the same issue here with 1.2.0 and M5Stack Atom Lite.

Works when reverting back to 1.1.0.

**Comment by i00** [comment]
Same here works with 1.1.0

Log:

Using 'COM3' as serial port.
Connecting........___
Detecting chip type... ESP8266
Connecting.....

Chip Info:
 - Chip Family: ESP8266
 - Chip Model: ESP8266EX
 - Chip ID: 00448915
 - MAC Address: BC:DD:C2:44:89:15
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 460800
Changed.
Unexpected error: Reading chip details failed: Timed out waiting for packet header

**Comment by dogcatfish** [comment]
Same here with Atom Matrix.  "Unexpected error: Reading chip details failed: Timed out waiting for packet header".
1.1.0 release worked fine for that too.

**Comment by i00** [comment]
@OttoWinter  ... why was this closed ... also older releases work as stated

**Comment by MaartenKleijwegt** [comment]
I'm still experiencing this issue with a m5stickc. Release 1.1 works while 1.3 doesn't

**Comment by Klarkin2** [comment]
I'm experiencing this issue with 1.3 as well
