### ISSUE TITLE
Writing to Flash Succeeds but Program Doesn’t Run

### ISSUE THREAD

**Issue by mastrumisciu** [esphome/esphome-flasher#170]
Hello, 
I'm using an ESP32 S3 WROOM - 1 and I'm able to upload a code by using Platformio. The code works perfectly.

When I try to upload with esphome flasher the firmware.bin file that platformio creates during the upload of the mentioned code the writing to flash succeeds but program doesn’t run.
(Something discussed here https://docs.espressif.com/projects/esptool/en/latest/esp32s3/troubleshooting.html but too complicate for me) 

After uploading the .bin file Arduino monitor and Platformio monitor shows:

invalid header⸮ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x7 (TG0WDT_SYS_RST),boot:0x8 (SPI_FAST_FLASH_BOOT)
Saved PC:0x40049b21
invalid header: 0xffffffff
invalid header: 0xffffffff
invalid header: 0xffffffff
invalid header: 0xffffffff
invalid header: 0xffffffff
invalid header: 0xffffffff
invalid header: 0xffffffff

I hope someone can help me fixing the issue.
Thank you!

**Comment by keith721** [comment]
There is an option in the latest version of ESPHome to build your firmware .bin files using either 
a) modern header
b) legacy header (for use with ESPHome-Flasher or esptool.py)

Be certain you are selecting the first option.
