### ISSUE TITLE
problem running esphome flasher in lubuntu 20.04

### ISSUE THREAD

**Issue by netweaver1970** [esphome/esphome-flasher#20]
Hi,
I tried to get it to run, installed all dependencies and now I got this traceback when starting :

```
Traceback (most recent call last):
  File "/home/geertsteyaert/esphome-flasher-master/esphome-flasher-master/esphomeflasher/gui.py", line 286, in OnInit
    frame = MainFrame(None, "esphome-flasher (Based on NodeMCU PyFlasher)")
  File "/home/geertsteyaert/esphome-flasher-master/esphome-flasher-master/esphomeflasher/gui.py", line 177, in __init__
    self._init_ui()
  File "/home/geertsteyaert/esphome-flasher-master/esphome-flasher-master/esphomeflasher/gui.py", line 226, in _init_ui
    serial_boxsizer.Add(reload_button, 0, wx.ALIGN_RIGHT, 20)
wx._core.wxAssertionError: C++ assertion "!(flags & wxALIGN_RIGHT)" failed at /home/wxpy/wxPython-4.1.0/ext/wxWidgets/src/common/sizer.cpp(2094) in DoInsert(): Horizontal alignment flags are ignored in horizontal sizers
OnInit returned false, exiting...
```

Any idea?

Thanks.

**Comment by didaccs** [comment]
I've got the same problem on ubuntu 18.04 and python 3.6

**Comment by didaccs** [comment]
As a workaround I uninstalled wxPython and esphomeflasher and install previous version of wxPython (4.0.7) and install again esphomeflasher, and now works fine!

**Comment by ymoona** [comment]
I can confirm that is a bug on Windows 10 as well. 
Also the work around to deploy wxPython 4.0.7 works on W10 (python 3.8.2)

**Comment by damitjimii** [comment]
Just fyi: 
pip3 uninstall package wxPython
pip3 uninstall esphomeflasher
pip3 cache purge
pip3 install wxPython==4.0.7.post2
pip3 install esphomeflasher

**Comment by MachinesJesus** [comment]
Thank you @damitjimii
