### ISSUE TITLE
serial port option states blank on Mac OS 

### ISSUE THREAD

**Issue by evonashion** [esphome/esphome-flasher#34]

**Comment by kerflop** [comment]
Having the exact same issue.  I am on a Mac with USBC ports, so not sure if that is an issue.

**Comment by MrVinceZ** [comment]
Do you plug the node directly to usb port ? 

Work fine with an usb hub between my MBP and the alimentation.

**Comment by drice78** [comment]
Having this same problem. I am connected to directly to the USB port on my mac mini.

**Comment by MrVinceZ** [comment]
> Having this same problem. I am connected to directly to the USB port on my mac mini. 

Maybe not enough power on USB port. Can you try with external alimentation ?

**Comment by juicejuice** [comment]
Change USB cables too, some of my USB cables are power only and the data pins are not connected. It will only show the USB ports when a valid USB UART device is connected.
