### ISSUE TITLE
Unexpected error: No module named '_random'

### ISSUE THREAD

**Issue by alve89** [esphome/esphome-flasher#48]
After successfully flashing a couple of ESP8266 I wanted to flash an AI-Thinker ESP32-Cam module with the binary compiled by ESPHome in Home Assistant.

The flashing ends with an error:

```
Using '/dev/cu.usbserial-A50285BI' as serial port.
Connecting.....
Detecting chip type... ESP32
Connecting...

Chip Info:
 - Chip Family: ESP32
 - Chip Model: ESP32D0WDQ6 (revision 1)
 - Number of Cores: 2
 - Max CPU Frequency: 240MHz
 - Has Bluetooth: YES
 - Has Embedded Flash: NO
 - Has Factory-Calibrated ADC: YES
 - MAC Address: AC:67:B2:38:AC:AC
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 460800
Changed.
 - Flash Size: 4MB
Unexpected error: No module named '_random'
```

The module works properly, I flashed it with some code from Arduino IDE and I was even able to get a video stream.

I'm on macOS 10.15.5 if this is helpful. How can I fix this problem?

**Comment by dberwig** [comment]
I am facing exactly the same issue with an ESP32 DOIT Devkit V1 on a macOS 10.15.7.
Also with 8266 no issues at all.
