### ISSUE TITLE
ESPHomeFlasher doesn't work on Mac

### ISSUE THREAD

**Issue by msiemers** [esphome/esphome-flasher#55]
I've Download it. Then klick on it an nothing works. I've got the Failure "You do not have the required access rights to open the "ESPHome-Flasher" program."

**Comment by Techsized** [comment]
same problem with my Mac

**Comment by Normanras** [comment]
It wasn't working for me, until I tried this. [See this issue.](https://github.com/esphome/esphome-flasher/issues/26#issuecomment-671061140).

Specifically, open terminal and try: 

`chmod +x ESPHome-Flasher.app/Contents/MacOS/ESPHome-Flasher`

Notice that if you were to open package contents of the app, you're making the final file executable. You can then test permissions by typing

`ls -l /Applications/ESPHome-Flasher.app/Contents/MacOS/`

You'll get some response like this: 

`total 30792
-rwxrwxrwx@ 1 normrasmussen  staff  15765270 Jul 30  2020 ESPHome-Flasher`

It should be noted that I tried `chmod` many times on the various files in the package and it didn't work. Especially after looking at permissions in terminal. Just before getting that response, I got `-rw-rw-rw-` and it didn't work. Specifically, it had to say `rwx` for it to finally open. 

Right clicking the app and going into "Get Info" and adjusting permissions that way also didn't actually fix the problem. 

I hope that helps!

**Comment by Techsized** [comment]
Tank you!!! It worked with no problem after entering the Command in the Terminal on my MacBook

**Comment by msiemers** [comment]
Thank you, works for me.
