### ISSUE TITLE
Feature request: "Offline-Mode" for flashing

### ISSUE THREAD

**Issue by gs-avionik-gunnar** [esphome/esphome-flasher#65]
When flashing same type of ESP32-modules each time the esphome-flasher seems to download the bootloader and partition-schema again. Would be nice, if the flasher would be able to cache these files, so you can use the tool without internet-connection.
I recommend the esphome-flasher for flashing firmware of my own project (https://github.com/gs-avionik-gunnar/GS-Traffic2WIFI) and some of the users reported me, that this features would be nice for them, too. That's why I think, it's not only me missing such function.
Anyway: Thanks a lot for that great tool!

**Comment by osmanovv** [comment]
Connected issue #10
