### ISSUE TITLE
x86 version has a trojan detected by Windows

### ISSUE THREAD

**Issue by terrag42** [esphome/esphome-flasher#9]
Virus detected as soon as it was done downloading:
Trojan:Win32/Zpevdo.A
The x32 version did not have a virus detection.

**Comment by terrag42** [comment]
I see this has been addressed in a different issue. Perhaps it should be removed from the list of releases.

**Comment by OttoWinter** [comment]
That is incorrect - the file does not have a virus/trojan.

Please actually read the discussion in the mentioned issue: https://github.com/esphome/esphome-flasher/issues/6
