### ISSUE TITLE
Program is reporting it has a virus.

### ISSUE THREAD

**Issue by tinseltunes** [esphome/esphome-flasher#92]
Not sure if you've had this before.
Virustotal.com is reporting it has a virus.
Antiy-AVL - Trojan/Generic.ASMalwS.34493BB - Cyren  W64/S-d6d7eeed!Eldorado
And 
Zillya Trojan.Disco.Win32.1337 - Acronis (Static ML)

Is this something you want to look into?

**Comment by OttoWinter** [comment]
Duplicate of https://github.com/esphome/esphome-flasher/issues/40
